[colors.primary]
background = "#1E1E2E" # base
foreground = "#CDD6F4" # text
# Bright and dim foreground colors
dim_foreground = "#CDD6F4" # text
bright_foreground = "#CDD6F4" # text

[colors.normal]
black = "#45475A" # surface1
red =     "#F38BA8" # red
green =   "#A6E3A1" # green
yellow =  "#F9E2AF" # yellow
blue =    "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan =    "#94E2D5" # teal
white =   "#BAC2DE" # subtext1
